name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
    
env:
  VERSION: 1.0.0

jobs:

  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Debuggin
      run: echo ${{ github.ref_type }}
    
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore dependencies
      run: nuget restore

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Run tests
      run: dotnet test --configuration Release

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore /p:Version=$VERSION
      
    - name: Pack
      run: dotnet pack --configuration $BUILD_CONFIG --output nupkgs /p:PackageVersion=$VERSION
      
    - name: Publish Nuget Package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    
